version: "3.9"
services:
  mysql-master:
    image: "mysql:8.0.27"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "3306:3306"
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/conf/my.cnf:/etc/mysql/my.cnf

  mysql-slave:
    image: "mysql:8.0.27"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: Asia/Shanghai # 指定时区
    ports:
      - "3307:3306"
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/conf/my.cnf:/etc/mysql/my.cnf
